import { defineConfig } from 'vite'
import { fileURLToPath, pathToFileURL } from 'node:url'
import path from 'node:path'
import { LOCALES, DEFAULT_LOCALE, getLocale, localeBasePath } from './src/i18n/locales.js'

const dirname = path.dirname(fileURLToPath(import.meta.url))

const SITE_URL = 'https://loopy.wtf'

/**
 * Build the hreflang block for a locale build
 *
 * Every locale lists every locale including itself, plus an x-default pointing
 * at the root. The root is the only URL that language-detects, which is
 * exactly what x-default is reserved for - every locale path below serves its
 * own language to every visitor and crawler, and never redirects.
 *
 * @returns {string} Indented <link rel="alternate"> markup
 */
function buildHreflangLinks() {
  const links = LOCALES.map(
    locale =>
      `  <link rel="alternate" hreflang="${locale.htmlLang}" href="${SITE_URL}${localeBasePath(locale.code)}">`
  )

  links.push(`  <link rel="alternate" hreflang="x-default" href="${SITE_URL}/">`)

  return links.join('\n')
}

/**
 * Substitute build-time tokens in index.html
 *
 * `{{message.key}}` comes from the locale dictionary; `{{@name}}` is one of the
 * computed values below. Doing this at build time rather than on load is the
 * whole point of the setup - the browser receives HTML that is already in the
 * right language, so there is nothing to swap and nothing to flash.
 *
 * @param {Object} options
 * @param {Object} options.messages - The active locale's dictionary
 * @param {Object} options.locale - The active locale descriptor
 * @param {boolean} options.isItch - Whether this is the single-locale itch build
 * @returns {import('vite').Plugin} Vite plugin
 */
function i18nHtmlPlugin({ messages, locale, isItch }) {
  const basePath = localeBasePath(locale.code)

  const computed = {
    '@htmlLang': locale.htmlLang,
    '@ogLocale': locale.ogLocale,
    '@canonical': `${SITE_URL}${basePath}`,
    // Shared files (icons, og image, videos) are deployed once at the domain
    // root and referenced absolutely, so the locale builds do not each carry a
    // duplicate copy. The itch build has no server, so it keeps them relative.
    '@asset': isItch ? './' : '/',
    '@manifest': isItch ? './manifest.json' : `${basePath}manifest.json`,
    '@hreflang': isItch ? '' : buildHreflangLinks(),
  }

  return {
    name: 'loopy-i18n-html',
    transformIndexHtml: {
      order: 'pre',
      handler(html) {
        return html.replace(/\{\{([@\w.]+)\}\}/g, (match, token) => {
          if (token.startsWith('@')) {
            return computed[token] !== undefined ? computed[token] : match
          }

          const value = messages[token]
          if (typeof value !== 'string') {
            throw new Error(
              `[i18n] index.html references "${token}", which is missing from ` +
                `src/i18n/messages/${locale.code}.js (or is a plural message, which markup cannot use)`
            )
          }

          // Meta tags and attributes are quoted with ", so any " in a
          // translation would end the attribute early
          return value.replace(/"/g, '&quot;')
        })
      },
    },
  }
}

export default defineConfig(async () => {
  const isItch = process.env.BUILD_TARGET === 'itch'

  // The itch build is a single self-contained bundle with no server to route
  // locales, so it always ships the default language.
  const localeCode = isItch ? DEFAULT_LOCALE : process.env.LOCALE || DEFAULT_LOCALE
  const locale = getLocale(localeCode)

  if (!locale) {
    throw new Error(
      `[i18n] Unknown locale "${localeCode}". Known locales: ${LOCALES.map(l => l.code).join(', ')}`
    )
  }

  const messagesPath = path.resolve(dirname, `src/i18n/messages/${locale.code}.js`)

  // Imported by explicit file URL rather than a template-literal specifier:
  // Vite bundles this config with esbuild, and a template-literal import gets
  // glob-expanded over the whole directory, which would drag src/i18n/index.js
  // and its `@i18n-messages` alias into a plain Node context where it cannot
  // resolve.
  const { default: messages } = await import(pathToFileURL(messagesPath).href)

  return {
    base: isItch ? './' : localeBasePath(locale.code),

    // Only the root build copies public/ into its output. The locale builds
    // reference those same files absolutely from the domain root, so the icons,
    // og image and ~1MB of tutorial videos are deployed once rather than once
    // per language. Their manifest.json is generated by scripts/build-locales.mjs.
    publicDir: isItch || !locale.path ? 'public' : false,

    resolve: {
      alias: {
        '@i18n-messages': messagesPath,
      },
    },

    define: {
      __LOCALE__: JSON.stringify(locale.code),
    },

    plugins: [i18nHtmlPlugin({ messages, locale, isItch })],
  }
})
